name:                avontuur-hs
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/avontuur-hs#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - ansi-terminal >= 0.9.1
  - megaparsec >= 7.0.5 && < 8

executables:
  avontuur-hs:
    source-dirs:      src
    main:             Main.hs
